### ISSUE TITLE
Find a bug in SlicedByteBuf in 4.0.36.Final netty

### ISSUE THREAD

**Issue by patrickseptem** [ganskef/LittleProxy-mitm#22]
When I invoked 
`public ByteBuf getBytes(int index, ByteBuffer dst)`

It throws index out of bounds exception. There is a wrong logic to invoke its checkIndex0 method. I have to roll back the version to 4.0.23 in my pom.xml, then the issue gone.

Could you consider to adopt another version if 4.0.36 is not required? Thanks.

At the end, appreciate you for contributing this project to open source.

**Comment by ganskef** [comment]
Hi Patrick,

LittleProxy-mitm don't require a specific Netty version. I have copied 
most of the pom.xml from LittleProxy since it was intended to be 
included or to be a module.

Whithin my application I use Netty 4.1.0.Final. It should be easy to add 
a Netty dependency in your pom.xml too. Please try to reproduce the 
problem with more recent versions up to 4.0.41.Final and post the results.

I'll have a closer look at this.


Regards Frank


Am 23.09.2016 um 10:37 schrieb patrickseptem:

**Comment by patrickseptem** [comment]
Hi Frank,

Just tried with other versions 4.0.37 & above, the bug is not fixed. Filed
an issue in https://github.com/netty/netty/issues/5864 also. Here I guess
you can add a known issue and suggest user downgrade the netty if they met
the same issue.

Thanks & Regards,
Patrick

**Comment by patrickseptem** [comment]
The issue is accepted by netty team as a defect.

**Comment by ganskef** [comment]
Hi Patrick, thank you for pointing this out! So we're waiting for Netty 4.0.42.Final ...

@jekh please note, we should plan a LittleProxy/LittleProxy-mitm release after integrating and testing this fix, I think.

**Comment by ganskef** [comment]
It is possible to use LittleProxy / LittleProxy-mitm with a more recent Netty 4.x version.
