### ISSUE TITLE
TryHostNameVerificationJava6 seems to be referencing the wrong method name.

### ISSUE THREAD

**Issue by zerkz** [ganskef/LittleProxy-mitm#5]
See https://github.com/ganskef/LittleProxy-mitm/blob/master/src/main/java/org/littleshoot/proxy/mitm/BouncyCastleSslEngineSource.java#L180
```
"tryHostNameVerification"

vs 

"trySetHostnameVerification"
```
as seen from below links.

See https://tersesystems.com/2014/03/23/fixing-hostname-verification/ and http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/sun/security/ssl/SSLEngineImpl.java#SSLEngineImpl.trySetHostnameVerification%28java.lang.String%29

**Comment by ganskef** [comment]
Hi Zack,

thank you for your interest. I've found this hack in the web. I've tried 
to find another class and method name, too. You see here, it is a bad 
thing, to use internal code. This is illegal for a reason and within 
Android, you will not find the com.sun package fragment.

I think the right way is to dig into Netty and its examples and find out 
a way to proper implement the protocol in the handler.


Regards Frank


Am 02.07.2015 um 05:06 schrieb Zack Whipkey:

**Comment by zerkz** [comment]
Yeah, reflection is always hacky to use like this. I think you might be right in digging deep into netty.

**Comment by ganskef** [comment]
I'l try to enable OpenSslContext instead of JdkSslContext to fix hostname verification with Java 6. 

Java 6 (and Android, and RoboVM) don't support this within it's ```javax.net.ssl.SSLParameters```. This is a security concern, depending the usage of the proxy. But, LittleProxy-mitm breaks the browsers security mecanism by intention and hides it from the user. Every user has to respect this.

**Comment by ganskef** [comment]
I've removed this obsolete method.
