### ISSUE TITLE
Unit/Integration tests fail sometimes due to netty.io responding with a 522.

### ISSUE THREAD

**Issue by zerkz** [ganskef/LittleProxy-mitm#8]
Noticed this pretty often. Are we accidently ddosing the site? Cloudflare seems to be up often.

Either way, we should add a check to pass the test if it 522's, so that we don't have to skip tests for installs often.

**Comment by ganskef** [comment]
Which test? It should be fixed with commit c907a0fd633bb026299f9b457bc4035eac8a1839.

I think, you have to merge upstream tracking, like described here: 
 1. https://help.github.com/articles/configuring-a-remote-for-a-fork/
 2. https://help.github.com/articles/syncing-a-fork/

If you've fetched my repo, you could try ```git cherry-pick c907a0f```. (But, I'm a Git newbie)

**Comment by ganskef** [comment]
I've cherry picked it into the netty_proxy_client branch, too. 
I'll investigate #4 to describe the intend the branch more clearly.

**Comment by zerkz** [comment]
Cool, does look like it was fixed in that comment. thanks!

**Comment by ganskef** [comment]
Ok, I'm going to close this.
